SatDump/SatDump

pipelines/X-Band.json
This will fix the occasional circle constellation on FY3E basebands.
=> Fix FY3E costas bw

src-core/modules/noaa/instruments/avhrr/module_noaa_avhrr.cpp
Hi, the sat_info.json identifies any NOAA sat like a NOAA15 so i fixed it.
=> Fix NOAA sat identification

resources/tles.json
Hi Aang,
I updated your tles.json file so map overlays work again.
=> Fix TLE update URL

satdump_cfg.json
Final CSWIR+NIR Natural Color added :)
=> MSU-MR CSWIR+NIR Natural Color

satdump_cfg.json
I got a bit tired of the toothpaste color in the MSU-MR clouds, so I tried adding a (very) experimental natural color CSWIR+NIR composite. It looks right on vegetated land, however the Sahara looks like it's covered in some sort of mold :joy: , so clearly some improvements are still needed. Feel free to reject if it seems too experimental for inclusion!
=> Added experimental MSU-MR Natural Color composite

pipelines/FengYun-4.json
=> Added LRIT frequency for FengYun-4

satdump_cfg.json
A new composite for HIRS, enhances the clouds. Works both day and night, during the night also highlights a bit the land.
Quoting Zbychu:
> finally somethomg nice with HIRS lol
=> Added cloud only HIRS composite

src-interface/viewer/radiation_handler.cpp, src-interface/viewer/scatterometer_handler.cpp
=> Fixed typos in ASCAT and SEM handlers

satdump_cfg.json, src-interface/viewer/radiation_handler.cpp, src-interface/viewer/scatterometer_handler.cpp
Ch3a and 3b got mixed up
(also includes a NIR composite that I pushed by mistake, sorry Aang...) 
NOAA 18
NOAA 19
=> Fixed day/night microphysics on AVHRR

satdump_cfg.json
Added NDVI composite (black and white only, maybe we can add a LUT later?)
=> Added NDVI vegetation index composite for AVHRR

satdump_cfg.json
Does not seem to work well enough as it does with METOP with the NOAA AVHRR. Maybe hold this one until calibration is done?
In any case, happy holidays :snowflake: :snowman_with_snow:
=> Added snow enhancement for AVHRR (Only METOP).

satdump_cfg.json
=> Fixed oopsie in snow enhancement

satdump_cfg.json
Fix for a small oopsie. Probably the last PR for 2022, so happy new year to everyone :smile:
=> added geo correction for snow

satdump_cfg.json, src-interface/recorder/recorder.cpp
changes as detailed in Matrix:
+ disabled 3a21/221 Mix, day/night microphysics and snow composite autogeneration
+ added NOAA natural color
+ added metop natural color
+ renamed meteor CSWIR+NIR to natural color
+ adjusted ndvi
+ added automatic microphysics
=> fixed compos (part 1)

pipelines/AIM.json, plugins/sdr_sources/rtltcp_support/rtltcp.cpp, plugins/sdr_sources/sdrpp_server_support/sdrpp_server.cpp, plugins/sdr_sources/spyserver_support/spyserver.cpp, satdump_cfg.json
Forgot to check the other plugins/sources.
=> More typo fixes

satdump_cfg.json
=> Added microphyiscs (day only) for meteor

README.md
Also i moved the [image](https://raw.githubusercontent.com/SatDump/SatDump/master/gui_example.png) below the quick start since it talks it being below and not above
=> [ci skip] Changes to README

satdump_cfg.json
=> Fixed composites as discussed (again)

satdump_cfg.json
"Natural" color composite for the instrument, mainly just adjusting the two channel values.
May clip over 1 in bright light, hard to tell with a sample size of 1 image
=> White balance composite for SIPMAI

plugins/meteor_support/meteor/module_meteor_lrpt_decoder.cpp
* fix invalid num bytes for memmove
=> meteor lrpt decoder bug fix

README.md, docs/Satellite-pipelines.md
list of all satellite processing pipelines and their parameters for CLI use.
=> add Pipeline Documentation

docs/Satellite-pipelines.md
=> Update satellite pipelines

satdump_cfg.json
Added following a discussion with co2esp on the matrix
=> Added 456, 445, autogen NO, fixed 654 not geo_correct

android/.settings/org.eclipse.buildship.core.prefs, plugins/analog_support/noaa_apt/module_noaa_apt_decoder.cpp, plugins/noaa_metop_support/noaa/module_noaa_instruments.cpp, satdump.desktop
=> Desktop file fix

android/.settings/org.eclipse.buildship.core.prefs, plugins/analog_support/noaa_apt/module_noaa_apt_decoder.cpp, plugins/noaa_metop_support/noaa/module_noaa_instruments.cpp
Added several modifications to show our love and respect to our beloved, truly unique and irreplaceable, APT satellite.
With this pull request, me and @Aang23 wish NOAA 15 a happy and long life with plenty of love, hugs and APT receptions.
we all :heart: NOAA 15
=> Modifications to show a lot of love to NOAA 15

satdump_cfg.json
=> Added rain composite for MHS

src-core/common/widgets/logger_sink.cpp, src-core/common/widgets/logger_sink.h
Fix scrolling the GUI log, which I broke in my last PR - sorry about that!
=> Fix scrolling GUI log when idle

satdump_cfg.json
Cloud Only
Low level WV
High level WV
=> Added water vapor channels to HIRS

satdump_cfg.json
Removed 421 and 221 as they were redundant and did not provide scientific information.
Added a WIP Surface Temperature algo, will be operational when calib done.
=> removed useless AMSU compos, added surf temp

satdump_cfg.json
Removed 2 broken composites
Added Soil moisture
=> Soil Moisture for MTVZA-GYa

satdump_cfg.json
Added:
* MHS equivalents
* Microwave airmass
* Surface Relative Temperature (AMSU compatible)
=> Showing some love to ATMS

docs/Projection.md, docs/Satellite-pipelines.md
=> improve documentation

plugins/sdr_sources/remote_sdr_support/plugin/remote_source.cpp, plugins/sdr_sources/remote_sdr_support/remote.h, plugins/sdr_sources/remote_sdr_support/server/main.cpp, plugins/sdr_sources/remote_sdr_support/udp_discovery.cpp, plugins/sdr_sources/remote_sdr_support/udp_discovery.h
=> SDR Server fix for Windows

pipelines/ViaSat.json
New sync word used on ViaSat-3 TLM.
=> New ViaSat-3 sync word :D

plugins/sdr_sources/remote_sdr_support/plugin/main.cpp, plugins/sdr_sources/sdrplay_sdr_support/main.cpp, src-core/common/dsp_source_sink/file_source.cpp, src-core/common/dsp_source_sink/file_source.h, src-core/common/rimgui.h, src-core/common/widgets/datetime.cpp
- Make File Source input honor default input directory settings
- Clean up Remote SDR Settings a bit; validate inputs and allow removing sources
- Fix some compiler warnings and typos
=> Several minor changes

src-interface/recorder/recorder.cpp
=> Show selected frequency preset

satdump_cfg.json
=> Made IASI useful

.github/workflows/all_build.yml
=> Fix nightly

src-core/imgui/pfd/portable-file-dialogs.h
Fixes "Save as" dialog on macOS. Before, it would not properly interpret the default path. Now it does.
**Before Fix**
**After Fix**
=> Fix "Save as" dialog on macOS

resources/credits.md, src-core/CMakeLists.txt, src-core/common/colormaps.cpp, src-core/logger.cpp, src-core/logger.h, src-interface/main_ui.cpp
=> Update Credits Screen

satdump_cfg.json
=> Added MWTS AMSU compo, MERSI-LL water vapor and MERSI-LL WX NO

plugins/meteor_support/meteor/instruments/msumr/lrpt_msumr_reader.cpp, plugins/meteor_support/meteor/instruments/msumr/module_meteor_msumr_lrpt.cpp
=> Fix dataset timestamp for Meteor M2-x LRPT

satdump_cfg.json
added NO, water vapor, removed useless 17-18-19, renamed others for clarity
=> MERSI-2 composite cleanup and additions

plugins/analog_support/noaa_apt/module_noaa_apt_decoder.cpp, plugins/elektro_arktika_support/elektro_arktika/lrit/module_elektro_lrit_data_decoder.cpp, plugins/fengyun2_support/fengyun2/svissr/module_svissr_image_decoder.cpp, plugins/fengyun4_support/fy4/module_fy4_lrit_data_decoder.cpp, plugins/gk2a_support/gk2a/module_gk2a_lrit_data_decoder.cpp, plugins/goes_support/goes/gvar/module_gvar_image_decoder.cpp, plugins/goes_support/goes/hrit/module_goes_lrit_data_decoder.cpp, plugins/others_support/orb/module_orb_decoder.cpp, src-core/common/widgets/waterfall_plot.cpp, src-core/common/widgets/waterfall_plot.h, src-ui/gl.h, src-ui/imgui/imgui_impl_opengl2.cpp, src-ui/imgui/imgui_impl_opengl2.h, src-ui/loading_screen.cpp, src-ui/loading_screen.h, src-ui/main.cpp
Use proper OpenGL 2 backends when OpenGL 2.1 fallback is needed
=> OpenGL 2.1 Fixes

src-core/common/image/image.h, src-core/common/image/image_processing.cpp, src-core/common/lua/lua_utils.cpp, src-core/products/image_products.cpp, src-core/products/image_products.h, src-interface/viewer/image_handler.cpp, src-interface/viewer/image_handler.h
Implement a Kuwahara Filter for despeckling
=> Add Despeckle

resources/descriptions/ColorGeneralIR.md
=> Fixed the image

plugins/sdr_sources/remote_sdr_support/iq_pkt.h, plugins/sdr_sources/remote_sdr_support/plugin/remote_source.cpp, plugins/sdr_sources/remote_sdr_support/server/pkt_handler.cpp
Fix some synchronization bugs, and fix 32-bit SDR Samples ("jumping" noise floor)
=> SDRServer Work

pipelines/CLUSTER.json
Sorta add CLUSTER-II FM lowrate downlink support. **!!!doesnt work yet, work in progress!!!**
=> Add initial CLUSTER support

pipelines/Cluster.json
Add a Cluster WBD demodulator (so far)
=> Add Cluster Highrate demodulator

pipelines/Cluster.json
Add Cluster 524k mode decoder (at the moment only down to cadu)
=> Add Cluster 524k decoder

plugins/cluster_support/cluster/module_cluster_instruments.cpp, plugins/cluster_support/cluster/module_cluster_instruments.h
Added audio muting for WBD, but needs to be checked. Possible ImGui issue/misunderstanding?
=> Add audio muting for WBD.

docs/Satellite-pipelines.md, pipelines/Meteor-M.json, plugins/goes_support/goes/hrit/module_goes_lrit_data_decoder.cpp, plugins/goes_support/goes/hrit/module_goes_lrit_data_decoder_proc.cpp, plugins/meteor_support/meteor/instruments/msumr/lrpt/segment.cpp, plugins/meteor_support/meteor/instruments/msumr/lrpt/segment.h, plugins/meteor_support/meteor/instruments/msumr/lrpt_msumr_reader.cpp, plugins/meteor_support/meteor/instruments/msumr/lrpt_msumr_reader.h, plugins/meteor_support/meteor/instruments/msumr/module_meteor_msumr_lrpt.cpp, src-core/common/lua/lua_utils.cpp
=> LRPT: Add "Fill missing data" option

plugins/sdr_sources/aaronia_sdr_support/aaronia_sdr.cpp, plugins/sdr_sources/airspy_sdr_support/airspy_sdr.cpp, plugins/sdr_sources/airspyhf_sdr_support/airspyhf_sdr.cpp, plugins/sdr_sources/bladerf_sdr_support/bladerf_sdr_sink.cpp, plugins/sdr_sources/bladerf_sdr_support/bladerf_sdr_source.cpp, plugins/sdr_sources/hackrf_sdr_support/hackrf_sdr_sink.cpp, plugins/sdr_sources/hackrf_sdr_support/hackrf_sdr_source.cpp, plugins/sdr_sources/limesdr_sdr_support/lime_sdr.cpp, plugins/sdr_sources/mirisdr_sdr_support/mirisdr_sdr.cpp, plugins/sdr_sources/plutosdr_sdr_support/plutosdr_sdr.cpp, plugins/sdr_sources/rtaudio_sdr_support/rtaudio_sdr.cpp, plugins/sdr_sources/rtlsdr_sdr_support/rtlsdr_sdr.cpp, plugins/sdr_sources/rtltcp_support/rtltcp.cpp, plugins/sdr_sources/sddc_sdr_support/sddc_sdr.cpp, plugins/sdr_sources/sdrplay_sdr_support/sdrplay_sdr.cpp, plugins/sdr_sources/soapy_sdr_support/soapysdr_sdr.cpp, plugins/sdr_sources/spyserver_support/spyserver.cpp, plugins/sdr_sources/usrp_sdr_support/usrp_sdr.cpp
Correct small spelling error found.
=> Correct small spelling error

plugins/inmarsat_support/aero/pkt_structs.cpp, plugins/inmarsat_support/stdc/packets_structs.h, plugins/noaa_metop_support/noaa/module_noaa_instruments.cpp, plugins/others_support/nat2pro/module_nat2pro.cpp, satdump.appdata.xml, satdump.desktop, src-core/imgui/implot/implot_demo.cpp
- Change license to match project
- Add some keywords
- Spelling errors
=> Spelling errors and packaging staff

src-core/common/tracking/obj_tracker/object_tracker.h, src-core/common/tracking/obj_tracker/object_tracker_rotator.cpp
Add Azimuth and Elevation rounding to avoid constant commanding of rotators which get confused with 3decimal places of precision.
=> Add AZ EL rounding.

Dockerfile, packages.runner
Use the package method for install, less possibility for discrepancies in the build process.
Updated the package dependencies.
Might also solve #710
=> Change docker build to deb package, update deps

pipelines/ACE.json, pipelines/Integral.json, pipelines/XMM-Newton.json, satdump_cfg.json, src-interface/recorder/recorder.cpp, src-interface/recorder/recorder.h, src-interface/recorder/recorder_proc.cpp
Semi-polished free space indicator for recording, still needs some stuff to be dealth with, like actually using the user-specified path and not a the root tree dir..... Line 549.
Also, it works only on linux and it doesn't update constantly as one would want. 
Oh yeah and there's Integral pipeline now :)... also XMM Newton and ACE (just down to soft bits as its using some arbitrary frame size).
=> Add a free space indicator.

.github/workflows/all_build.yml, plugins/sdr_sources/mirisdr_sdr_support/mirisdr/libmirisdr.c, windows/Configure-vcpkg.ps1
Fixes issues on some types of Windows machines
=> WinUSB RAW_IO

src-cli/record.cpp
=> fix building with ZIQ disabled

satdump_cfg.json, src-interface/recorder/recorder.cpp, src-interface/settings.cpp
Added a setting that determines whether the LO input is locked when the source is active.
=> LO lock setting added

plugins/sdr_sources/plutosdr_sdr_support/plutosdr_sdr.cpp, plugins/sdr_sources/plutosdr_sdr_support/plutosdr_sdr.h
- Pluto sdr enumeration (usb/ip)
- Available gain Added
- Rf input selection (rx1/rx2) for pluto Rev C
- CS8/CS16 format (only with tezuka firmware)
=> Pluto fixes and new features

plugins/inmarsat_support/aero/libacars/list.c, plugins/inmarsat_support/aero/libacars/list.h, src-core/libs/sol2/config.hpp, src-core/libs/sol2/sol.hpp
Resolves this issue, with both sol2 failing on compilers GCC >= 15, fixed also thanks to @mk0x55 the inmarsat issue, where some parameters were for some reason not added to the provided functions from a header file:
https://github.com/SatDump/SatDump/issues/959
=> Updated sol2.hpp and inmarsat fixed by @mk0x55

resources/pipelines/DSCOVR.json, resources/pipelines/Elektro_Arktika.json, resources/pipelines/FengYun-3.json, resources/pipelines/GOES.json, resources/pipelines/GeoNetCast.json, resources/pipelines/Himawari.json, resources/pipelines/JPSS.json, resources/pipelines/MSG.json, resources/pipelines/MTG.json, resources/pipelines/NOAA.json, resources/pipelines/Orbcomm.json, resources/pipelines/Others.json, resources/pipelines/Saral.json, resources/pipelines/Sentinel-6.json, resources/pipelines/Stereo.json, resources/pipelines/TUBSAT.json, resources/pipelines/Tianwen.json
Referenced external docs and https://www.satdump.org/Satellite-List/
Should be all good. Removed L band freqs from noaa gac, given that l band gac is done for the time being
=> Added frequencies, moved saral to the right place

resources/pipelines/Others.json
=> add sstv parameters
