CMakeLists.txt
src-core/CMakeLists.txt
src-core/modules/spacex/falcon_video_encoder.cpp
src-core/modules/spacex/falcon_video_encoder.hpp
src-core/modules/spacex/module_falcon_decoder.cpp
src-core/modules/spacex/module_falcon_decoder.h

I know that this is a little bit outdated since the Falcon9 stream is currently encoded.
But @Aang23 suggested adding this code since it's a lot of work was done.
Probably this module can be used for some other/future video feed. Currently, it's in the Falcon decoder module but can be moved and renamed. 
**The module is not specific for the Falcon or SpaceX or any specific format** It's based on libavformat/libavcodec and can read any input video feed and convert it to an h264 mp4 file with real-time text overlay (optionally).
The module automatically detects all video and KLV data streams. Each stream's data will be saved in a separate file:
video_0.mp4, video_1.mp4, data_0.klv, and so on.
Damaged frames are dropped so the resulting file can be played with any player.
**I introduced a …

Add video transcoder module, initially designed for SpaceX Falcon 9 stream

---

src-core/modules/oceansat/instruments/ocm/module_oceansat_ocm.cpp

Adds a "221" like composite and another true color like composite.

Add 882 and 662 composites to Oceansat-2 OCM

---

.gitignore
src-core/common/widgets/snr_plot.cpp
src-core/common/widgets/snr_plot.h
src-core/modules/meteor/module_meteor_hrpt_demod.cpp
src-core/modules/meteor/module_meteor_hrpt_demod.h
src-core/modules/module_bpsk_demod.cpp
src-core/modules/module_bpsk_demod.h
src-core/modules/module_oqpsk_demod.cpp
src-core/modules/module_oqpsk_demod.h
src-core/modules/module_qpsk_demod.cpp
src-core/modules/module_qpsk_demod.h
src-core/modules/noaa/module_noaa_dsb_demod.cpp
src-core/modules/noaa/module_noaa_dsb_demod.h
src-core/modules/noaa/module_noaa_hrpt_demod.cpp
src-core/modules/noaa/module_noaa_hrpt_demod.h
src-core/modules/terra/module_terra_db_demod.cpp
src-core/modules/terra/module_terra_db_demod.h

This PR adds a new readout to (hopefully) all demodulators which shows the peak SNR of the signal that is being demodulated.

Add peak SNR readout to all demodulators

---

.github/workflows/windows_build.yml
src-cli/main.cpp
src-ui/main.cpp

Added a -h/--help switch and also added some extra explanatory text to the logger on command line switches. This came about after a friend didn't know how to turn on DC Blocking from the command line. Happy to take suggestions on changing what I have added to make it clearer.
We could also split up the help switch into a bigger, more useful set of guidance further down the line.

Added some extra guidance on command line switches and also a -h/--help switch

---

pipelines/composites/fengyun_mersill.json.inc
src-core/modules/coriolis/instruments/windsat/windsat_reader.cpp

This PR fixes a compile error regarding bswap16 on all supported platforms.

Fix compile error on windsat for all platforms

---

src-ingestor/main.cpp

Added Content-Type header to avoid getting "not well-formed" error in Firefox when loading JSON file with XMLHttpRequest.

Add Content-Type header

---

libsdr/sdr/spyserver.cpp

If the specified samplerate was not available, the default was the max. This change makes the default the next biggest samplerate to the one specified.

Changed default spyserver samplerate to next biggest

---

README.md

I noticed while building that `-DBUILD_LIVE=ON` is no longer needed (existing).

remove live-build option in README

---

satdump_cfg.json

* Day microphysics (`ch1, (1-ch3)^2.5,(1-ch4)`), info [here](http://www.virtuallab.bom.gov.au/files/8014/4100/7389/DayMicrophysicsRGBTOTALoneslide_Compatibility_Mode.pdf), **does not look to spec on METOP** but is still useful, works very well on POES.
* Night time microphysics (`(1-ch5)-(1-ch4),(1-ch4)-(1-ch3),(1-ch4)`), info [here](https://www.star.nesdis.noaa.gov/goes/documents/QuickGuide_GOESR_NtMicroRGB_final.pdf), **must be white balanced or will look way off**, works very well on METOP and POES.
* Basic false color composite (`ch1, ch8, ch15`) info [here](http://d33.infospace.ru/d33_conf/sb2018t2/9-18.pdf)
* Cloud only (`ch29, ch28, ch1`) uses low and high bands to produce an image of only clouds (from LeanHRPT)
Day/night time microphysics will probably work well on GOES and JPSS, …

Added new composites

---

README.md

`-DBUILD_ZIQ=1` no longer needed since release of SatDump 1.0.0 BETA

Remove ZIQ build flag

---

satdump_cfg.json

For some reason the equalization parameter was missing on HIRS and AMSU composites (but present on MHS), rendering them almost useless (I thought HIRS had finally given up the ghost on NOAA18 but later when receiving the DSB signal, it turns out it still works and it was just this simple mistake)

Fixed missing equalization on HIRS and AMSU

---

plugins/sdr_sources/plutosdr_sdr_support/plutosdr_sdr.cpp
plugins/sdr_sources/plutosdr_sdr_support/plutosdr_sdr.h

- Check the return value of iio_buffer_refill (not doing so caused satdump to sometimes crash when plutosdr was disconnected)
- Added a automatic reconnect feature for PlutoSDR IP

PlutoSDR fix and automatic reconnect

---

pipelines/AIM.json
pipelines/Jason-3.json
pipelines/Others.json
pipelines/Work-In-Progress.json

Some are still empty, like SMOS or NEOSSAT.

Add Frequencies

---

docs/SDR-Options.md

RTL-TCP options were missing from the documentation. This pull request adds all available options, and fixes a typo

Document RTL-TCP

---

satdump_cfg.json

new compos as discussed on the matrix. 
Can't support 543 due to incorrect frequency and noisy channel 3; 
Can't support ATMS 16-17-18 due to missing 88 and 165 GHz frequencies

Added AMSU equivalents for MTVZA

---

src-core/common/widgets/snr_plot.cpp

Displays the average value of the recent SNR history used for the graph

Display average SNR value

---

src-core/common/widgets/snr_plot.cpp

Added check that only counts snr_history values greater than 0 and lower than peak_snr to prevent issues during the first 200 counts before the history is fully populated (seems to be Windows specific)

Avg snr display fix

---

resources/projections_settings/noaa_18_avhrr.json

This PR fixes a bug when using the "Correct" feature with NOAA-18 GAC dumps.
[Example NOAA-18 GAC FRM for testing](https://www.dropbox.com/s/segmjrler9lzibt/2023-04-04%200321%20UTC%20-%20NOAA%2018.frm?dl=1)
**Without this PR:** the image is stretched far too wide when applying correction:
**After applying this patch:** (which uses the same corr_width as NOAA 19), the correction appears more natural:

Fix NOAA-18 GAC Correction Width

---

README.md
plugins/goes_support/goes/grb/data/glm/glm_parser.h
plugins/sdr_sources/sdrpp_server_support/sdrpp_server/smgui.h
plugins/sdr_sources/spyserver_support/spyserver/networking.cpp
src-core/common/detect_header.cpp
src-core/common/detect_header.h
src-core/common/dsp/demod/constellation.h

Fixes build issues due to <cstdint> and <stdexcept> not being included in certain files
Also changes the readme.md to say make -j`nproc` instead of make -j4 to use all cores if someone has more than 4
The commit names are a bit messed up since i used the github web ui and had to commit after every change
Builds fine on arch linux, without disabling any sdrs

Fix build issues due to missing definitions

---

plugins/goes_support/goes/hrit/module_goes_lrit_data_decoder_proc.cpp

**On the GOES-R HRIT downlink, NOAA is sending two separate products with the same name and timestamp every hour**: "OR_ABI-L2-DSIF-*.lrit," where * is the current ABI mode and timestamp. Under the hood, the difference between the DSI files is that one is the DSI CAPE product, while the other is DSI Lifted Indexes (LI). These products are documented [here](http://cimss.ssec.wisc.edu/goes/OCLOFactSheetPDFs/ABIQuickGuide_BaselineDerivedStabilityIndices.pdf).
**With SatDump's current behavior**, the second file simply overwrites the first, and the first file is lost.
**With this PR**, SatDump looks for existing files with the same filename. If it exists, it tries appending a -2, -3, etc to the end until it finds an available filename, then saves the file. This way, no data is lost.
**FYI**, …

Don't overwrite duplicate-named raw images on GOES HRIT

---

pipelines/GOES.json
plugins/goes_support/goes/hrit/module_goes_lrit_data_decoder.cpp
plugins/goes_support/goes/hrit/module_goes_lrit_data_decoder.h
plugins/goes_support/goes/hrit/module_goes_lrit_data_decoder_proc.cpp

Allow saving all .LRIT files for GOES-R HRIT, instead of just unknown/DCS files. Useful for analysis in other programs.
If the lrit file is segmented, the segment number is appended to the name to keep it from overwriting the previous segment (matches goeslrit behavior).

Add option to GOES HRIT pipeline to save .lrit files

---

plugins/goes_support/goes/hrit/data/goes_r_fc_composer.cpp
plugins/goes_support/goes/hrit/data/lrit_data.h
plugins/goes_support/goes/hrit/module_goes_lrit_data_decoder.cpp
plugins/goes_support/goes/hrit/module_goes_lrit_data_decoder_proc.cpp

This PR makes a number of changes within the GOES-R HRIT Plugin:
- **Fixed the Segmented LRIT decoder when segments are missing:** There was logic there before to save partially-written data, but it no longer worked. I'm guessing some other changes broke it. This resulted in incomplete files never being saved, and the buffer would be "carried forward" to the next image. 
This resulted in a loss of data, as well as strange things when 2 back-to-back images of the same channel had missing segments: if between them, all the segments were there, it would save a Frankenstein combination of the segments in the buffer.
This PR fixes it, and along with it, this issue: #273.
- **Moved around logic on when to save FD color images:** Necessitated by the first change
- **Fixed timestamp on full color …

GOES-R Segmentation Fixes

---

src-core/common/lrit/lrit_demux.cpp
src-core/common/lrit/lrit_file.h

In the current implementation, SatDump's LRIT demuxer will discard the entire LRIT file/segment if any packet within it has a CRC failure. In image files, this results in the file being entirely missing, or (if segmented) large areas of the image are gone.
This PR changes the LRIT Demuxer so it will keep LRIT files/segments with bad packets if:
- The LRIT file is already in progress
- The LRIT header is already complete
- The LRIT Sequence Flag is 0 (a continuation of data from previous packets, but not the last)
- The LRIT file type is 0 (image), and has an ImageStructureRecord
This results in significantly better images, especially in cases where there was only 1 or 2 CRC failures. Tested on GOES-R HRIT and GK-2A LRIT only.
**GOES 16 - Before & After** (click to zoom in)
**GK-2A - …

LRIT Demuxer - Salvage some LRIT files with bad packets

---

plugins/gk2a_support/gk2a/key_decryptor.cpp

On Windows, the automatic download and extraction of the GK-2A encryption key fails on extraction. If they key is already in place, the decoder otherwise works. This PR fixes the error. 
**Error log when trying to automatically install the key:**
```
[17:52:57 - 24/07/2023] (I) Downloaded COMS Decryption sample! Decompressing...
[17:52:57 - 24/07/2023] (I) Extracted!
[17:52:57 - 24/07/2023] (I) CRC is valid!
[17:52:57 - 24/07/2023] (I) Application Time header: 2011020907300000 (09/02/2011 07:30:0)
[17:52:57 - 24/07/2023] (I) (65) = 09D93692ED07867F858472F4ADE3BF7B
[17:52:57 - 24/07/2023] (I) (66) = 0D5EFC37229EC7AD858472F4ADE3BF7B
[17:52:57 - 24/07/2023] (I) (67) = D6572762B67E8367858472F4ADE3BF7B
[17:52:57 - 24/07/2023] (I) (68) = 9F8D6B078050782F858472F4ADE3BF7B
[17:52:57 - 24/07/2023] …
```

Fix GK-2A pipeline crash when the key isn't already installed

---

src-core/common/dsp/io/baseband_interface.h
src-core/common/dsp_source_sink/file_source.cpp
src-core/common/ziq.cpp
src-core/common/ziq.h

This PR is pretty straight forward: it adds the ability to seek through ZIQ files in the recorder. My original intent was to fix the bug where ZIQ playback gets stuck at 100% and does not loop like other recorded file types - and I got a bit carried away 😄 
The repeat fix is really fast, but there is a delay in seeking from the beginning of the file to near the end. Incrementing forward, or scrolling towards the beginning, is nearly immediate. On my machine with the "worst case" I regularly run (a 15-minute S8 ZIQ at 6 Msps) can be scrolled from 0% to 95% in 15 seconds. Not too bad, but not nearly as fast as a simple `istream::seekg`.
Let me know your thoughts - I'm not sure how much the performance can be improved, or how well it would work with higher sample rate ZIQs. I like having the …

Add ability to scroll ZIQ Recordings

---

src-core/modules/demod/module_demod_base.cpp

This PR changes the logic that sets the min/max of the offline FFT display. Instead of looking at the entire frequency range, it only looks at the "middle" 80%. The logic takes frequency shift into account, and the entire FFT is still shown.
**Reason:** I have a few SDRs with a rather extreme drop-off at the edges. With current logic, this results in poor scaling in the offline FFT since it takes the drop-off into account:
**After the changes, the FFT is much more useful:**
To be honest, I'm not sure how much this problem exists for others. It certainly depends on the SDR. If you feel my situation is an edge case, I'll be perfectly fine if this does not get merged.
Thanks!

Ignore edges when calculating offline FFT Plot min/max

---

src-core/common/image/image_jpegio.cpp

Mirrors the behavior of other `save_imageformat` functions to `Image::save_jpeg` to keep it from making empty JPEG files

Fix empty JPEG file on no data

---

src-core/common/dsp/io/wav_writer.h

Here a proposal to switch to RF64 when max size of WAV reached.
Implemented according https://tech.ebu.ch/docs/tech/tech3306v1_0.pdf using the WAV/RF64 compatibility format with a JUNK placeholder section. This allows to switch to RF64 when the size limit is reached without needing to insert a new section into the header. This stays compatible with standard WAV format for files below 4GB.
Fix #339

[WAV export] Support wav files over 4GB by switching to RF64 if required

---

README.md

Added commands for installing the needed dependencies for Red Hat Systems like Fedora, RHEL,...
Tested with Fedora 37 and Fedora 38 (clean installs).

Added dependencies for building on Red Hat Systems

---

satdump_cfg.json
src-interface/main_ui.cpp
src-interface/main_ui.h
src-interface/recorder/recorder.cpp
src-interface/status_logger_sink.cpp
src-interface/status_logger_sink.h
src-interface/viewer/viewer_projection.cpp
src-ui/CMakeLists.txt

**Adds a status bar at the bottom of the UI**, which shows the last log item that is `LOG_INFO` or greater, regardless of log level setting. Can be turned off in settings.
It gives a nice indicator within the UI of background tasks - especially ones that were invisible before, like live mode product processing and TLE updating. It's especially useful on Android and Linux (when launched via the .desktop file) since the console is not available in these situations. It's also potentially a great vessel for Easter Eggs 😉.
**Info during live decode**
**Info on live decode product processor**
**TLE Updates**
<hr>
**As a related question, not addressed in this PR:** what are your thoughts on suppressing the console in release builds of satdump-ui on Windows?
This would more-or-less mirror the …

Add Status Bar to UI

---

src-interface/recorder/recorder_proc.cpp

When milliseconds activated, this changes the filename for example from
`2023-08-05_18-02-45-1691258565.534000_16000000SPS_2284000000Hz.s16`
to
`2023-08-17_11-42-00-006_1000000SPS_100000000Hz.f32`
which seems the originally intended format.
(3 digits milliseconds instead of epoch float with microsecond resolution).
The shorter fix would have been to juste replace `timeValue_precise` with `ms_val` on line 250, but this way it is a little more C++ish in my view. I can also change to the simpler variant PR.

[Filename] Use HH-MM-SS-MSS instead of HH-MM-SS-Epoch.Ss in filename when millisecond precision activated

---

src-core/common/tracking/tle.cpp
src-interface/recorder/recorder.cpp

This PR fixes 2 crashes:
- **Fixed a crash when opening the Recorder Debug widget,** when no source is currently started.
- **Fixed a crash when opening the satellite list in the tracker widget after updating TLEs,** if SatDump already had TLEs loaded. Technically this was due to the in-memory TLE list getting empty vector items on update.

UI Crash fixes

---

plugins/noaa_metop_support/noaa/module_noaa_gac_decoder.cpp
src-core/common/dsp_source_sink/file_source.h
src-core/common/widgets/logger_sink.cpp
src-core/common/widgets/logger_sink.h
src-core/modules/products/module_products_processor.cpp
src-interface/status_logger_sink.cpp

This PR has 3 fixes:
- **Don't reset the log in the GUI once there are more than 1000 log items.** Instead, pop the first item off the top of the buffer once the max is reached. I also implemented mutex locking within this widget - I saw this change cause some crashes otherwise.
- **Fix GAC frame count in log.** It always displayed 0 before
- **Fix file source playback "fast-forward" bug in the recorder section on Windows.** High-samplerate file playbacks would play as fast as the computer could handle it, after playing for a few minutes on Windows (probably on 32-bit Linux, too). After some debugging, it looks like it's because of the `total_samples` variable within `dsp::DSPSampleSource`.
On Windows, `long` is only a 32-bit integer - regardless of OS architecture - which is way too …

Various fixes

---

plugins/meteor_support/meteor/deint.cpp
plugins/meteor_support/meteor/module_meteor_lrpt_decoder.cpp
plugins/meteor_support/meteor/module_meteor_lrpt_decoder.h

* First:
```diff
- std::vector<int> average_bit(8 * period);
+ std::vector<int> average_bit(8 * period + 8, 0);
```
this needs because out of bound is possible here:
```c++
tmp |= (average_bit[best_idx + i] > 0 ? 1 << i : 0);
```
when `best_idx` is greather than `8 * period - 8`
I also removed manual filling of vectors with zeros, because it is available using the constructor.
* Second:
```diff
- buffer = new int8_t[ENCODED_FRAME_SIZE];
+ _buffer = new int8_t[ENCODED_FRAME_SIZE + INTER_MARKER_STRIDE];
+ buffer = &_buffer[INTER_MARKER_STRIDE];
```
`buffer` indented because out of bounds is possible here:
```c++
deinterleave(dst, dst + offset, len);
```
when `offset < 0`
The indent of `INTER_MARKER_STRIDE` is due to this expression:
```c++
offset = offset > INTER_MARKER_STRIDE / 2 ? offset …
```

fix out of bound in deinterleaver for meteor lrpt decoder

---

CMakeLists.txt
plugins/analog_support/noaa_apt/module_noaa_apt_decoder.cpp
plugins/dmsp_support/dmsp/module_dmsp_rtd_instruments.cpp
plugins/goes_support/goes/grb/data/payload_assembler.cpp
plugins/inmarsat_support/aero/module_aero_parser.cpp
plugins/inmarsat_support/stdc/module_stdc_parser.cpp
plugins/sdr_sources/sdrpp_server_support/sdrpp_server/networking.cpp
plugins/sdr_sources/spyserver_support/spyserver/networking.cpp
plugins/stereo_support/stereo/instruments/secchi/rice_decomp.cpp
src-core/common/cli_utils.cpp
src-core/common/dsp_source_sink/file_source.cpp
src-core/common/dsp_source_sink/file_source.h
src-core/common/image/image_drawing.cpp
src-core/common/lua/lua_utils.cpp
src-core/common/wav.cpp
src-core/core/pipeline.cpp
src-core/nlohmann/json_utils.h
src-core/products/image_products.h
src-core/products/radiation_products.h
src-core/products/scatterometer_products.h
src-interface/pipeline_selector.h
src-interface/recorder/recorder_proc.cpp
src-interface/recorder/tracking/tracking_widget_backend.cpp

**This PR makes a few changes** - not the ones I was going to make, mind you. The first change I intended on making, and the rest just ended up happening on the way 😎. Everything else will have to be in a later PR.
- **Adds "fast mode" to the GUI recorder tab when playing back from a file source.** This lets the file play back/process as fast as possible. I found myself needing to decode just part of a file, or use the screen as a poor man's way to convert a ziq to s8/s16. The ability to run through it at full speed is helpful in both situations. I tested the change with a few decoding pipelines and it seems to work OK - I assume this is safe to do, but I'm sure you have more insight.
- **Cleaned up compiler warnings on Windows** to make the log more useful in finding problems. This …

File source fast mode and other fixes

---

android/app/src/main/java/MainActivity.kt
android/loading_screen.cpp
android/loading_screen.h
android/main.cpp
satdump_cfg.json
src-core/core/style.cpp
src-core/core/style.h
src-interface/loader/loader.cpp
src-interface/loader/loader.h
src-interface/main_ui.cpp
src-interface/main_ui.h
src-interface/pipeline_selector.h
src-ui/loading_screen.cpp
src-ui/loading_screen.h
src-ui/main.cpp

This PR detects display scaling (desktop) or display density (Android) and correctly sets UI scaling based on that. Also makes the program aware in changes in DPI (i.e. when moved to an external monitor) and scales automatically.
The UI scale setting is still there, but only if the user wants to make the UI bigger or smaller as a preference. It's no longer necessary on high DPI screens; 1.0 should always be the developer-intended size, regardless of display type/scaling.
Still testing on macOS

Auto Display scaling

---

src-ui/main.cpp

Disables DPI awareness on older versions of GLFW since it's not supported. Display scaling in user settings should still work. Fixes #371

Fix GLFW 3.2 Support

---

pipelines/Meteor-M.json
pipelines/NOAA.json
src-core/common/widgets/datetime.cpp
src-core/common/widgets/datetime.h
src-core/common/widgets/logger_sink.cpp
src-core/core/params.h
src-interface/pipeline_selector.h
src-interface/recorder/tracking/tracking_widget_autotrack.cpp

This PR adds a timestamp input widget for use in pipeline parameters.
- It returns a double, just like the float param type.
- Setting it to "Auto" returns -1, otherwise it returns the specified unix timestamp, in UTC, with sub-second accuracy.
- CLI users should still specify a Unix timestamp.
**I tweaked a handful of other things in this PR as well:**
- Fix Floating Console scroll location on open - if the log was not actively being written to, it would scroll to the top instead of bottom on open
- Fix double scrollbar in pipeline selection of scheduler
- Made the GUI Param table's "key" column auto-fit to the key name, and the value column fills the rest of the available space. This makes the table more readable on smaller areas like the scheduler and live decoding.

Timestamp input widget

---

macOS/Info.plist
src-core/CMakeLists.txt
src-core/core/style.cpp
src-core/core/style.h
src-ui/loading_screen.h
src-ui/main.cpp

This PR improves display scaling for retina displays on macOS. It also improves font rendering on the same screens to make text look crisper.
`style::macos_framebuffer_scale()` is a bit of a workaround: we should be able to use `ImGui::GetIO().DisplayFramebufferScale` to get the same value, but it doesn't work consistently for me. Maybe I'm doing something wrong, but the native API seems to work more reliably.
Fixes #376

macOS: Improve Retina Support

---

.github/ISSUE_TEMPLATE/bug_report.md
src-core/core/config.cpp
src-core/logger.cpp

A few macOS-specific changes:
- **Made code to find the user's Documents folder more robust** - it's possible to make your Documents folder somewhere else other than ~/Documents.
- **Save SatDump's log to Library/Logs/satdump.log**. I dropped the "s" on macOS only so the log shows up nicely in Console.app - it even works live!

Mac-Specific Path Changes

---

src-core/common/map/map_drawer.cpp
src-core/common/map/map_drawer.h
src-core/products/processor/image_processor.cpp
src-interface/viewer/image_handler.cpp
src-interface/viewer/image_handler.h

* `Capital Only`: Draw only Capitals
* `Regional Capital Also`: Draw Capitals and Administrative centers
* `All (by Scale Rank)`: Draw all cities by Scale Rank. The higher the "Scale Rank", the smaller cities will be drawn.

Choose other cities types/size instead Capitals only and draw on map overlay

---

plugins/sdr_sources/sdrplay_sdr_support/sdrplay_sdr.cpp

There was no case in this function before, so the checkbox would do nothing.
It will still only be useful when Tuner 2 is selected, because the duo doesn't have bias on Tuner 1.

Support setting bias on RSPduo

---

macOS/Entitlements.plist
macOS/bundle.sh
plugins/sdr_sources/remote_sdr_support/udp_discovery.cpp

Does what it says in the title - the executable is available under SatDump.app/Contents/MacOS, with the other executables.
I tested and ruled out the need for com.apple.developer.networking.multicast. With this type of distributed app, I think the only valid entitlements are the ones listed at https://developer.apple.com/documentation/security/hardened_runtime. Adding the multicast entitlement causes the app to crash.
I tested up to macOS 13 with no issues

Mac SDR server

---

plugins/audio_sinks/portaudio_audio_sink/CMakeLists.txt

Please merge the PR on vcpkg before this one since it is the one that actually moves the file: https://github.com/Aang23/vcpkg/pull/2
This PR fixes audio output for live APT on Windows. It looks like the version of portaudio you have in vcpkg expects the DLL to be named `portaudio_x64.dll`. With the current name, this cryptic message is left in the error log:
```
[15:50:38 - 15/09/2023] (T) Loading plugin ./plugins\portaudio_audio_sink.dll...
[15:50:38 - 15/09/2023] (E) Error loading ./plugins\portaudio_audio_sink.dll! Error : ".\plugins\portaudio_audio_sink.dll": The specified module could not be found.
```
The "specified module" in this case is portaudio_x64.dll, not portaudio_audio_sink.dll. It looks like the actual module that fails to load gets lost along the way.

Fix PortAudio DLL Name

---

CMakeLists.txt

In this PR:
- Fix shortcuts to have the correct "Start in" path. Fixes problem of not all plugins loading. Modified form of PothosSDR's solution for the same problem.
- Prompt to uninstall old versions before installing the new version. Without this, old files can get left behind when updating, which may cause problems in the future.

More Windows Installer Tweaks

---

plugins/sdr_sources/remote_sdr_support/plugin/main.cpp
plugins/sdr_sources/remote_sdr_support/plugin/remote_source.cpp
src-core/nlohmann/json_utils.cpp

**For your review:**
This PR implements a way for plugins to save their settings within the main settings file. Each plugin can create an entry under `config::main_cfg["plugin_settings"]["<plugin-id>"]`, where it can store any values it wants as a JSON object. Implemented for the Remote SDR plugin.
The primary change needed was to invert the JSON diff logic, which allows JSON objects to exist in the user settings that do not exist in the main configuration.
I did some testing on various OSs and it seems fine, but another set of eyes would be great for a change like this.

Save Plugin Settings

---

src-interface/recorder/tracking/tracking_widget_interface.cpp

This is more portable; the cast can cause errors on some toolchains. When [compiling with musl](https://github.com/void-linux/void-packages/actions/runs/6291786525/job/17080505741?pr=45340), for example:
error: cast from 'std::nullptr_t' to 'ImGuiTableFlags' {aka 'int'} loses precision

Replace (ImGuiTableFlags)NULL with ImGuiTableFlags_None

---

src-interface/recorder/recorder.cpp
src-interface/recorder/recorder.h
src-interface/viewer/viewer.cpp
src-interface/viewer/viewer.h
src-ui/main.cpp

Various bug fixes, all stemming from one report - 
- Fix bug where viewer/recorder panel ratio would not save correctly in some circumstances (thanks @RAD750)
- Fix bug where quickly resizing viewer/recorder panels could create a large margin between the panels
- Fix bug where resizing the recorder panel to specific sizes would cause a crash
- Clean up viewer/recorder panel ratio logic - for simplicity, left panel width is no longer maintained on window resize. Instead, it scales proportionally with the window.
- Remove old workaround that was used to help the panel ratio saving logic, but is no longer needed. It also resulted in an extra frame at the end of program termination in non-Android builds

Viewer/Recorder Fixes

---

src-core/common/image/image.cpp
src-core/common/image/image_pbm.cpp

- Use P5 instead of P4 for grayscale images
- Make the PBM loader more resilient to the number of whitespaces in the header
- Fix some warnings

PBM fix-ups

---

src-interface/viewer/image_handler.cpp
src-interface/viewer/image_handler.h
src-interface/viewer/radiation_handler.cpp
src-interface/viewer/radiation_handler.h
src-interface/viewer/scatterometer_handler.cpp
src-interface/viewer/scatterometer_handler.h
src-interface/viewer/viewer.cpp
src-interface/viewer/viewer.h
src-interface/viewer/viewer_projection.cpp

- Fix crash when attempting to close dataset that has an ongoing operation
- Fix crash when loading and closing datasets at the same time
- Fix random crash when projection starts in the middle of the viewer panel being rendered

Viewer threads

---

plugins/fengyun3_support/fengyun3/instruments/mwri/mwri_reader.cpp
plugins/fengyun3_support/fengyun3/instruments/windrad/windrad_reader.cpp
plugins/others_support/cryosat/instruments/siral/module_cryosat_siral.cpp
src-core/common/resizeable_buffer.h

This PR fixes a few memory-related issues in the FY plugin:
- Fixes a bug where `ResizableBuffer` would try to `delete` a null pointer if the object never had `create()` run, crashing the program
- Removed extra 1000 in all instances that `ResizableBuffer::create()` is called. This function already multiplies all inputs by 1000, so multiplying the input by 1000 beforehand seems redundant and results in large memory allocations. On Windows, the 2nd call to `ResizableBuffer::create()` in `WindRADReader` failed with `std::bad_alloc` before this change (despite having the memory available).
I verified that the failsafe call to `ResizableBuffer::resize()` is never called within `WindRADReader` on some test FY 3E HPT data I have, and all data is saved.

Memory Fixes

---

src-core/core/config.cpp

Fix default output paths on Windows when the user folder has Unicode characters

[Windows/Installed] Fix default output paths

---

src-ui/imgui/imgui_image_adv.cpp
src-ui/imgui/imgui_image_base.cpp
src-ui/main.cpp

Extend mipmapping to all supported old GL versions. Mipmapping is now used in the viewer on all devices

Mipmap on OpenGL 2 / GL ES 2.0

---

README.md

Added the installation instructions for alpine linux. 
Wasn't able to test GUI, as I was building it on a headless system.

Add Alpine linux instructions

---

plugins/eos_support/eos/instruments/modis/calibrator/modis_calibrator.h
plugins/eos_support/eos/instruments/modis/calibrator/modis_calibrator_utils.cpp
plugins/eos_support/eos/instruments/modis/calibrator/modis_emiss_table.h

- Move some of the MODIS calibration data to the heap. Over 3MB was going on the stack, which is too much for Windows (and, if compounded, would become a problem on Linux too). As a result, MODIS now works on Windows
- Fixed buffer overrun in `modis_emiss_table.h`
- Add missing checks into precomputeVars to prevent errors on scans missing data. Fixes additional issues in sample data from @RAD750 
- Ensure all members of `ValsPerScan` are initialized to prevent corrupt product.cbor files when some scans have missing data

Various MODIS fixes

---

CMakeLists.txt
README.md

I tested all of these changes on a MacBook Pro with an M3 Pro SOC running macOS 14 Sonoma and Xcode 15.
The main changes have been made to the include & link directories in homebrew.
Those seem to have moved to a new location on Apple Silicon Macs. On my older Intel machine the usual includes work just fine which is why these new changes are only applied on Apple Silicon Macs. 
The build instructions for fftw3 also had to be updated as the ARM SOCs do not support SSE or AVX, those are for x86 only. 
Otherwise no other changes are required as of now.

Update CMakeList and build instructions for Apple Silicon Macs

---

src-interface/recorder/recorder.cpp

This threw me off at first, I thought it was the main LO (center freq) because I didn't notice the huge 000.000.000 right below, but it's really just offset tuning

LO offset label

---

src-core/common/overlay_handler.cpp

Added forgotten font initialization that caused cities to not appear in the final image.

fix autogened cities overlay

---

resources/scripted_compos/NightFire.lua
resources/scripted_compos/ndwi.lua

Standardize LUA scripts to not use get_calibrated_value since it causes issues when channel counts are different on different downlinks (ie APT and HRPT)
Fixes Nighttime fire detection for APT

Change 2 LUA composites

---

Dockerfile

Build with 8 cores, add: --build-arg CMAKE_BUILD_PARALLEL_LEVEL=8
The CMAKE_STAGING_PREFIX better matches the cross compiling style to the multistage

Docker: change build options, control parallel build

---

resources/scripted_compos/underlay_with_clouds.lua
resources/scripted_compos/underlay_with_clouds_lut.lua
satdump_cfg.json
src-core/common/image/composite.cpp
src-core/common/image/composite.h

- Add `get_channel_image(int)` function to Lua to get a copy of the channel specified in the config, as an object. You can call `:equalize()`, `:white_balance()`, etc on this object within Lua
- MCIR/MSA/etc: equalize source before compositing for a more reliable result; re-balanced tuning for new algorithm
- Add MSA for MSU-MR
- Slight memory reduction when making composites

Composite improvements

---

plugins/inmarsat_support/aero/module_aero_parser.cpp
plugins/inmarsat_support/stdc/module_stdc_parser.cpp

Just a small change to the JSON structure for the station_id when being sent via UDP. As well as sending along the program name and version to make it more identifiable when being ingested.

Inmarsat UDP : Update station_id formatting and send SatDump Version

---

plugins/sdr_sources/sdrplay_sdr_support/sdrplay_sdr.cpp
plugins/sdr_sources/sdrplay_sdr_support/sdrplay_sdr.h

Hi,
This adds support for SDRplay's RSP1B. According to the website, it is an enhanced hardware revision of RSP1A (https://www.sdrplay.com/rsp1b/).
For this reason, I've just added the RSP1B hardware id wherever A was used (except for the name in the UI).
It works for me with SDRplay API v3.14.0 (on MacOS 14.2.1, Intel), which aded support for RSP1B. The device is detected correctly and I can use the radio, just I didn't have a chance to get outside and test an actual reception with it.
Note: The application build requires to manually set  DYLD_LIBRARY path when launching, i.e. `DYLD_LIBRARY_PATH="/Library/SDRplayAPI/3.14.0/lib/" ./satdump-ui`
Looking at the linked SDRplay plugin: It seems odd the libsdrplay_api is linked with a relative path only. 
```
ebirn@oldboy SatDump % otool -L …
```

Add support for SDRPlay RSP1B

---

pipelines/NOAA.json
plugins/analog_support/noaa_apt/module_noaa_apt_decoder.cpp
plugins/analog_support/noaa_apt/module_noaa_apt_decoder.h

- Switch from using range to Standard Deviation to compute validity of APT data
- Evaluate specific parts of the wedge for validity instead of the entire thing
- Don't crop on wedges, but rather the Standard Deviation of a given line's wedge column (allows showing OK data above/below detected wedges)

APT Tuning

---

satdump.appdata.xml
satdump.desktop

According freedesktop.org "Encoding" key is deprecated and should be removed. Also there should be at least one Main Category.

Remove deprecated Encoding and add Main Category

---

pipelines/NOAA.json
plugins/analog_support/noaa_apt/module_noaa_apt_decoder.cpp
plugins/analog_support/noaa_apt/module_noaa_apt_decoder.h
plugins/noaa_metop_support/noaa/module_noaa_instruments.cpp
resources/projections_settings/noaa_15_avhrr.json
resources/projections_settings/noaa_18_avhrr.json
resources/projections_settings/noaa_19_avhrr.json

- Fix scaled values, used for calibration, etc
- Switch space parsing over to use Standard Deviation, like everything else in APT.
- Fixed some bugs where the timing lines would be added into the space average instead of excluded
- Use timing lines to align passes to the correct time

APT Improvements

---

.dockerignore
.gitignore
Dockerfile
README.md
docker-compose.yml

Added .env file to control build and running of container. 
Updated documentation.
Removed volume for settings, located in shared directory instead.

Change docker to user instead of root

---

src-interface/viewer/image_handler.cpp

When saving images, the filename scheme was always `instrument_composite.png`. This is troublesome when dealing with more than one composite at once, since saving a new one will overwrite the old one, is also troublesome when more than one pass is being processed. This PR gives filenames a new scheme:
`<Timestamp_of_product>_<Instrument>_<Channel/composite>_<Composite_used_if_applicable>.png`
For example: `2024-07-06_22-48-36Z_msu_gs_composite_Thermal-Channel.png`

Make saved image filenames include date and composite used

---

pipelines/DMSP.json
plugins/dmsp_support/dmsp/instruments/ols/ols_rtd_reader.cpp
plugins/dmsp_support/dmsp/instruments/ols/ols_rtd_reader.h
plugins/dmsp_support/dmsp/module_dmsp_rtd_instruments.cpp

Uses two not very efficient loops that compare each bit of the frame sync words to what they should be and if at least 88 out of the 96 bits are in a correct position then the frame is marked as sync. Recovers considerably more image data, the original implementation would lose a line to a bit flip anywhere in the 96 bit sequence.
For even better implementation the fixed threshold could be made into a variable accessible from the UI via the RTD pipeline
Before/after;

Better OLS RTD line frame sync

---

src-core/common/dsp/io/baseband_interface.h

When both BUILD_ZIQ and BUILD_ZIQ2 are not defined, an orphaned else causes the build to fail

Fix build error when ziq is disabled

---

Dockerfile
packages.builder
packages.runner

Reordering the install to allow it to automatically pull in any new dependencies, adding the -dev packages is still needed for any new features to be built.

Add docker dependencies, reorder install

---

pipelines/Geoscan.json
plugins/cubesat_support/geoscan/module_geoscan_decoder.cpp
plugins/cubesat_support/geoscan/module_geoscan_decoder.h

This update allows receiving data packets from the new GEOSCAN satellite platform, which has several amateur radio satellites that will be launched into orbit on November 5. These satellites are planned to broadcast images, but the transmission protocol is not yet fully approved and may change, so I have not added a decoder for this, but will do it later when we decide on the image data packaging format.

Support for the new GEOSCAN satellite platform

---

src-cli/help_general.cpp
src-cli/help_general.h
src-cli/main.cpp

Hi,
I found that the CLI version hasn't any "help" or "-h" like many utility in commande line. They were some information once you were in "Live", "record", etc. but nothing at the basic "satdump" level
You can now use: satdump -h  or satdump help to get some information and get you started.
Hoping that will help people

Create help menu for the CLI version

---

src-interface/viewer/viewer.h
src-interface/viewer/viewer_projection.cpp

This PR was based off my work with large layer sets, sometimes 30+ at a time. Sometimes you genuinely do want to disable ALL of the layers before reselecting new ones from scratch in a different area of the world. Sometimes you want to enable just one layer out of a set to make an image, but hate having to manually click on EVERY inactive layer to turn them all back on.
This change fixes this issue and also gets rid of the hack that always ensures that one layer is selected. This was apparently to protect against crashes, but adding code to lockout the projection buttons if no layers are active in the layer set gets around this.
Happy to take suggestions to change bits of this or improve it, but I am struggling to think of anything I have changed that is "game-breaking" and a few brief …

Add Enable/Disable all layers buttons, lock-out projection buttons with zero active layers

---

satdump_cfg.json

MSU-GS channel 3 has the center wavelength at 0.86 µm, making ch3,ch3,ch1 much closer to the range of AVHRR 221 than the previous ch2,ch2,ch1
**AVHRR/3**
1 - 0.63 µm (0.58-0.68)
2 - 0.862 µm (0.725-1.00)
**MSU-GS**
1 - 0.57 µm (0.5-0.65)
2 - 0.72 µm (0.65-0.8)
3 - 0.86 µm (0.8-0.9)

Updated incorrect MSU-GS 221 composite channels

---

plugins/fengyun2_support/fengyun2/svissr/module_svissr_image_decoder.cpp
plugins/fengyun2_support/fengyun2/svissr/module_svissr_image_decoder.h
resources/pipelines/FengYun-2.json

S-VISSR is prone to misplaced lines because of the lack of FEC, this PR addresses that by adding a  **user toggleable** option to enable rudimentary, **sequential-based** correction - if the current counter is the last one plus one, assume the next will be this one plus one and so on.
There are drawbacks to this, since the Earth can be deformed and imagery might be cut unexpectedly. For this reason, I made it toggleable - if you know what you're in for, you can use it, otherwise it can remain off. Note that it is VERY useful in cases such as 5-10 dB where a few lines might be misplaced even though imagery is more than presentable.
Results:
Inspired by https://github.com/Foxiks/fengyun2-svissr-corrector

Added rudimentary S-VISSR correction

---

pipelines/Elektro_Arktika.json

This bandwidth offers a **significantly** stabler lock at low SNRs, shouldn't have an effect on better ones. A stable lock at 0.8 dB is possible with it, while the old pipeline sometimes unlocked even at 2 dB.

New Elektro-L LRIT pll bandwidth

---

plugins/goes_support/goes/gvar/module_gvar_image_decoder.cpp
plugins/goes_support/goes/gvar/module_gvar_image_decoder.h

(PR MOVED FROM #924 )
GOES GVAR is very prone to corruption due to lacking FEC, this PR makes imagery significantly more presentable at low SNRs by applying several types of correction:
- **The header is triple redundant, majority law is applied between them now**
- **The scan count is gathered by using majority law from within a series** (Blocks are transmitted 1 through 11, in that order, with each one having the same scan count) to ensure the scan count is consistent between all frames
- **Block IDs are recovered in cases where the block Id gets corrupted in the middle of a series** (I.e. 1,2,3,66,5,6,7,8,9,10)
- **Bit masks are now applied to ensure impossible scenarios won't happen** (Image width and scan count)
- **Junk data is thrown out before it can get processed by checking …

Added GOES GVAR correction

---

plugins/elektro_arktika_support/elektro_arktika/instruments/msugs/module_msugs.cpp

I noticed that CADU has a backup for VCID. Checking it helps to extract data with low SNR more effectively.

Double VCID check in CADU for MSU-GS

---

resources/credits.md
resources/pipelines/Elektro_Arktika.json

GGAK loves to get stuck at +/- 3 kHz of the signal and never sync, I have seen a significant improvement with this PLL bandwidth with the pipeline eventually jumping to the correct one. 0.025 has been reported to work good as well, I have only tested 0.02 though.

Improves GGAK sync performance

---

plugins/fengyun2_support/fengyun2/svissr/module_svissr_image_decoder.cpp

The S-VISSR decoder didn't properly pull the SC/ID out because of a silly mistake; the Sector ID block was missed. 
This created a 2 byte offset on the data which is handled properly for the rollback scan detection (Documentation word number is **2**, zero based indexing makes it **1** (-1), sector ID makes it **3** (+2)), but it was forgotten with SC/ID - documentation is 90, zero based indexing makes it 89 **(This was used before!)**, but the sector ID block makes the correct byte position 91.
Tested on FengYun 2H and 2G data.
Also removes the composite autogeneration code since that's using a deprecated system.

Adds in S-VISSR SC/ID detection

---

src-interface/explorer/explorer.cpp

Tried casting nullptr to a string, cpp wasn't happy and crashed

Fixed crash on paste & go when clipboard doesn't have text

---

resources/instrument_cfgs/goesn_imager.json
resources/instrument_cfgs/msu_gs.json

Adds a color + IR merge without an underlay to Elektro (MSU-GS) and GOES-N (IMAGER)

Adds color+ir merges
